version: '3.0'
services:
  app:
    build:
      context: ./project
      dockerfile: ./../docker/Dockerfile
    image: my-laravel-app
    container_name: zoo-app
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"
    volumes:
      - ./project:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
  database:
    image: mysql:8
    container_name: zoo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./config/init.db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
